### PR TITLE
Add --devel option to Inertia formula

### PR DESCRIPTION
**Pull request by bobheadxi**
```bash
bobbook:homebrew-tap robertlin$ brew install inertia-rc.rb
==> Downloading https://github.com/ubclaunchpad/inertia/releases/download/v0.4.0-rc2/inertia.v0.4.0-rc2.darwin.386
Already downloaded: /Users/robertlin/Library/Caches/Homebrew/inertia-rc-0.4.0-rc2.386
🍺  /usr/local/Cellar/inertia-rc/0.4.0-rc2: 3 files, 13.5MB, built in 1 second
bobbook:homebrew-tap robertlin$ inertia-rc --version
inertia version v0.4.0-rc2
```

## updated

using Homebrew's `devel` spec:

```bash
bobbook:homebrew-tap robertlin$ brew install inertia.rb --devel
==> Downloading https://github.com/ubclaunchpad/inertia/releases/download/v0.4.0-rc2/inertia.v0.4.0-rc2.darwin.386
Already downloaded: /Users/robertlin/Library/Caches/Homebrew/inertia-0.4.0-rc2.386
🍺  /usr/local/Cellar/inertia/0.4.0-rc2: 3 files, 13.5MB, built in 1 second
bobbook:homebrew-tap robertlin$ inertia --version
inertia version v0.4.0-rc2
```

### CODE REVIEW

**Comment by iKevinY** [comment]
I'm thinking it might be better to use one of Homebrew's [unstable formula versions](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#unstable-versions-devel-head) for this purpose, otherwise there might be some annoying clashing with having the two formulae installed. That'll involve changing the formula to build from source, which could be useful anyways — if you want I can try doing that over the weekend though!

**Comment by bobheadxi** [comment]
Oh man I swear I was looking for how to do something like that for AGES but I couldn't find it wtf

> That'll involve changing the formula to build from source

I think this is something that might be nice if you have some time to give it a crack!

It looks like to implement a `devel` spec we can avoid building from source though? I'll give this a try

**Comment by bobheadxi** [comment]
Works awesome 😁 see  004ec1c

```bash
bobbook:homebrew-tap robertlin$ brew install inertia.rb --devel
==> Downloading https://github.com/ubclaunchpad/inertia/releases/download/v0.4.0-rc2/inertia.v0.4.0-rc2.darwin.386
Already downloaded: /Users/robertlin/Library/Caches/Homebrew/inertia-0.4.0-rc2.386
🍺  /usr/local/Cellar/inertia/0.4.0-rc2: 3 files, 13.5MB, built in 1 second
bobbook:homebrew-tap robertlin$ inertia --version
inertia version v0.4.0-rc2
```

then attempting to install it normally gives you a good error:

```bash
bobbook:homebrew-tap robertlin$ brew install inertia
==> Installing inertia from ubclaunchpad/tap
Error: inertia 0.4.0-rc2 is already installed
To install 0.3.0, first run `brew unlink inertia`
```

**Comment by iKevinY** [comment]
Oh nice — best of both worlds (didn't know you could do that with the `devel` block)! 👍

**Review by iKevinY — APPROVED** [review]

**Comment by bobheadxi** [comment]
Chucked in some quick documentation about this too 📚

**Pull request merged**
